### ISSUE TITLE
I love it

### ISSUE THREAD

**Issue by trusktr** [kbrsh/moon#124]
My only pain point is having to use `foo.set()` and `foo.callMethod()` to set properties or call methods.

Can `.set()` be replaced with accessors, and `callMethod()` with actual method calls? That's pretty much the major difference on the API side compared to Vue.

This is a bunch of extra verbosity that I'd like to avoid.

The speed compared to Vue is really nice. What is fundamentally different about it compared to Vue on the internals that makes Moon faster?

**Comment by kbrsh** [comment]
Glad you like it!

Replacing `.set` with accessors would make the initialization step slower than it is now. I did make [a plugin](https://jsfiddle.net/9L3fdhao/2/) for it a while back, and it will add getters/setters to all of the (shallow) properties of the object.

In v1, you will be able to use `.set` with an object, similar to React's `setState`. This should hopefully make updating multiple properties easier.

I do agree on making `callMethod` better, but methods are really only there for templates to access, not for other methods to call. Currently, if you'd like to call a method like normal, you can do:

```js
const method = this.get("method");
method("foo");
```

This works because methods are automatically merged with data when initializing a component, and it's also how a template is able to access a method.

Moon is faster than Vue in most cases because of it's compiler. It has the ability to mark entire trees as static and skip them when updating components.

For example, having something like:

```html
<div id="app">
  <h1>{{dynamic}}</h1>
  <div>
    <p>Static Content</p>
    <button>Click Me</button>
  </div>
</div>
```

Moon will mark the second `div` as static, and will only update the `h1`.

**Comment by unseen1980** [comment]
Just played with moon and it looks nice. I like the simplicity. 
https://codepen.io/unseen/pen/RZdJYq 

Good job @kbrsh 👍

**Comment by trusktr** [comment]
> Currently, if you'd like to call a method like normal, you can do:
> 
> ```js
> const method = this.get("method");
> method("foo");
> ```

That's still a bit much. Is there a specific reason why it can't be that way right now?

In Vue, when using `ref`s, it is sometimes useful to get a reference to some component and call a method on it as part of it's public API. 

I suppose instead of having `play`/`stop` methods on a `cool-video` element we can just let it have a `playing` or `paused` attribute, etc.

**Comment by trusktr** [comment]
Simon in the Meteor forums noted [a few differences](https://forums.meteor.com/t/alternative-view-layer-libraries-alternatives-to-blaze-angular-react/38092/7) between Moon and Vue:

> ### Moon doesn’t support inline expressions for events
> 
> Some other things that work in Vue but not in Moon:
> ```
> {{value || 'default'}}
> ```
> In Moon, this will display ‘undefined’ as text if value doesn’t exist.
> ```
> {{toggle ? 'On' : 'Off'}}
> 
> This will display “On” even when toggle is false
> 
> I then tried:
> ```
> {{toggle == 'true' ? 'On' : 'Off'}} and {{toggle == true ? 'On' : 'Off'}}
> 
> They would always display “Off” even when toggle was true :confused:

**Comment by kbrsh** [comment]
Thanks @trusktr!

I'll definitely try to make the method API simpler. As for the inline expressions--they won't be supported inside of `m-on`, but they _will_ be supported in v1.

In fact, they are supported in v0.11.0 if you add parenthesis around the expression:

```html
{{ (toggle ? 'On' : 'Off') }}
{{ (value || 'Default') }}
```

In v1 this will be done for you. For now, you can use a plugin for a simple method API.

```js
const MoonMethods = {
  init(Moon) {
  	const MoonInit = Moon.prototype.init;
    Moon.prototype.init = function() {
      const methods = this.$options.methods;
      if(methods !== undefined) {
      	for(let name in methods) {
        	this[name] = methods[name];
        }
      }
    	MoonInit.call(this);
    }
  }
};

Moon.use(MoonMethods);

const app = new Moon({
  methods: {
  	foo() {
    	alert("Foo Called!");
    }
  }
});

app.foo();
```

**Comment by sudomabider** [comment]
I've just finished a small plugin with Moon to be embedded in all our clients. Knowing Vue already it was super easy to pick up Moon. And being as lightweight as it is, the plugin turns out to be awesomely small in size. I feel this is exactly where Moon shines (pardon the pun). And I mostly quite like the current state of its API. We really don't need yet another full blown framework in my opinion :smile:

To be clear, I'm all for making things simpler and easier to use. But please don't let v1 get too much bigger :sweat_smile:

**Comment by kbrsh** [comment]
@sudomabider Awesome! Glad to know that you like the size and flexibility. v1 is being developed on this repo (on the "master" branch), and is still 7kb minified and gzipped, but comes with

* A more optimizing compiler
* `insert` system
* `static` directive
* Inline expressions
* A lot more that I can't name off the top of my head

**Comment by sudomabider** [comment]
@kbrsh Thanks for the great work. I can already see lots of breaking changes coming up in the next release. Looking really good. 

Any estimate on v1's release? Would be awesome if we can release our project on v1.

**Comment by kbrsh** [comment]
@sudomabider Yup, there are a lot of breaking changes. It's a result of me rewriting almost all of Moon.

v1 should be released in the next couple of months, and I will probably be releasing a migration tool that can list things you need to change and what you should change.

**Comment by trusktr** [comment]
> v1 is being developed on this repo (on the "master" branch), and is still 7kb minified and gzipped, but comes with

If possible, make as many of the new things opt-in plugins.

**Comment by kbrsh** [comment]
@trusktr That is probably not going to happen. If you were using Moon before (without any bad practices), upgrading should be fairly easy. I can't make them into plugins because v1 is a rewrite of Moon itself.

**Comment by kbrsh** [comment]
Closing in favor of #141
