### ISSUE TITLE
Component error with multiple Moon instances [v0.11.0]

### ISSUE THREAD

**Issue by sudomabider** [kbrsh/moon#125]
Instantiating multiple Moon instances produces a `cannot redefine property` error on the component.

```
const Moon = require("moonjs");
require("./components/app.moon")(Moon);

...

new Moon({
    el: "#element-1",
    template: `<app/>`
});

new Moon({
    el: "#element-2",
    template: `<app/>`
});
```

Seems like the same instance of `app` is being used in both root instances.

Any tips?

**Comment by kbrsh** [comment]
This is a restriction that isn't documented (will be added in v1 docs), but basically, a component cannot have another component as it's direct child. This is because Moon cannot track both of them.

In this case, the root element will be replaced with a component, and there isn't really a way to handle this correctly. Should both components be kept? If the root component's data changes, how should it go about updating the DOM?

You need a wrapper element, like `<div><app/></div>`, to prevent the root Moon instance from sharing the same DOM element with the component.

**Comment by sudomabider** [comment]
@kbrsh Thanks for the explanation. I'm not sure if this addresses the error though.

FYI this works perfectly fine for me. According to your comment this shouldn't work?
```
const Moon = require("moonjs");
require("./components/app.moon")(Moon);

...

new Moon({
    el: "#element-id",
    template: `<app/>`
});
```

I tried putting in a wrapper for the component as below and am seeing the same error.
```
const Moon = require("moonjs");
require("./components/app.moon")(Moon);

...

new Moon({
    el: "#element-1",
    template: `<div><app/></div>`
});

new Moon({
    el: "#element-2",
    template: `<div><app/></div>`
});
```

More specifically this is happening in `initComputed` when it tries to define a computed property but somehow is doing it on an existing instance.

**Comment by kbrsh** [comment]
That's really weird. Are you sure `data` is a function is those components? (If you want helpful errors, be sure to use `const Moon = require("moonjs/dist/moon.js")` to load the development version of Moon).

**Comment by sudomabider** [comment]
@kbrsh You're spot on. Somehow when I read the docs I was under the impression this is where Moon differs from Vue. Turns out it's exactly the same...my bad. Closing issue now.

**Comment by kbrsh** [comment]
Haha no problem. The reason this is done is because Moon caches all options of components, including data. So when a new component is created, the same data property is shared. When a there is a function, the data of each instance is set to the output, instead of sharing the same data.
