### ISSUE TITLE
Proposal: templating as a plugin

### ISSUE THREAD

**Issue by LeviSchuck** [kbrsh/moon#144]
As a complete package, I think having templating built in and on by default is a good thing.

I ran into confusion and bugs along the way and ended up just writing my own render code.
A fair amount of the code base seems to be dedicated to template parsing and custom props that are transformed at compile time.

What if templating and the likes was just a plugin? What if there was a lighter moon?

This is just an idea, and I'm cool with it being shot down.

**Comment by kbrsh** [comment]
The reason I've dedicated so much time to a compiler is because I want templates to be how you define the view. You can always switch to custom render functions if you really want more control, but the compiler can generate extremely optimized code for you.

Another big advantage of using templates is that it is much easier to get started with. You don't need to include a JSX transform, or write custom render functions using confusing things like nested ternaries.

In fact, the compiler generates much more optimized code than JSX, and this is because HyperMoon isn't meant for everyone to use. It's a strict syntax that the compiler generates code for.

If you don't mind me asking, what exactly was confusing about the template system? If there are any bugs, I'd love get them fixed.

**Comment by LeviSchuck** [comment]
To set some expectations, I'll start with where I come from.

First, I'm mostly a back end guy, I want things to be simple and straight forward. However if I run into issues involving stability, I am fully willing to do the raw work myself to have immediately functioning behavior, rather than waiting for a fix. When I am comfortable changing the vendor dependency, that's when I'll address breaking changes due to my raw work. (I am not used to having such responsiveness from an author 👍 )

Secondly, as for comparing to JSX and all, I don't have experience beyond a hello world there. Most of my professional frontend work is in sad ol' Angular JS 1.x and I've come to really dislike magic things that are hard to trace. It may seem insane to most, but I find generating raw DOM more pleasant and predictable than working with angular. (in fact, that's what I have right now in one of my projects, which I would like to replace with moon soon)

Thirdly, I come to moonjs over vue or preact or angular et al because I want something small, fast, and still comprehensible if I need to get into the raw details. _I prefer to avoid ceremony and hidden details only a 1 or fewer lines in documentation describe. `m-literal` for passing rich objects fell into this description._

Finally Monx + Moon was the biggest selling point for me. It is very important to be predictable and Monx was the answer to that. Mutable component specific internal variables are not predictable, require listeners, on init, on change, on mount, two way binding, all sorts of messes that I have put up with for far too long.

As for templating bugs and confusion that I have encountered, I'll list a couple that I've hit along the way.

1. If the last element has a conditional `m-`, the template engine tries to replace an empty text node with the div, but the parent DOM element where `replaceChild` is called doesn't have such a child, so it throws a browser DOM exception. I get the feeling that browsers replace or ignore empty text nodes.
2. I really liked moonify, but the version compatibility right now made that a non-option. Scoped CSS was pretty cool too and would make it more embeddable than what I got now.
3. I don't like having HTML templates inside of quotes in JS if it is more than a line.
4. I'm not sure what the cause is, or if my manual work is related, but it seems like events don't bubble up if not captured by the immediate parent. Say, C emits "clicked", B does not capture it, A does, A contains B, B contains C. 
5. Seeing `"" + content + ""` seemed silly from the JS generated by the template engine. This may be fixed by now, but it diminished my belief in its quality and compactness. 
6. I wish there were waaaaaay more sanity checks in the dev version (as opposed to the minified version), I saw you using `"development" !== "production"` in some places which was a really neat trick I've never seen before. 
7. The whole `m-literal:prophere` thing was a little verbose and hard to find. 
8. Self terminating tags often made the templater unhappy, even though I never would or planned to put content inside some of these things.
9. Manual stuff usually resulted in a cleaner runtime DOM structure. Having everything fit in the inspector and not needing to open a nest of 15 layers to see things is desired. (Oh man, angular ionic or whatever I saw on a coworker's screen while helping them with an ipad was an intimidating and a waste of time to explore.)
10. Maybe my use case is silly (which you'll see below), but having a switch case style meta tag would be nice--with the requirement that it does not introduce a DOM parent-child relationship in the real DOM for reasons described above.
11. Having HTML in the `index.html` that the user receives is a no-go for me, so something like the TODO MVC example with everything there is not an option. I need something embedabble.

In some of the code below, you'll see one thing I am doing which would totally take less lines if in an html template, but refused to act properly _without runtime errors_ via a template version due to template weaknesses I experienced.

```
      var contents = [];
      for(var effectKey in data.effects) {
        var effect = data.effects[effectKey]
        var attrs = {};
        if (effect.type == 'text') {
          attrs.type = 'text',
          attrs.text = effect.value;
        } else if (effect.type == 'image') {
          attrs.type = 'image',
          attrs.image = effect.value;
        } else if ("development" !== "production") {
          console.log("Unknown effect.");
        }
        contents.push(m("message", {attrs: attrs}, {dynamic: 1}, []));
      }
      if (data.waiting) {
        contents.push(m("message", {attrs: {type: 'waiting'}}, {dynamic: 1}, []));
      }
      if (data.prompting) {
        contents.push(m("prompt", {attrs: {options: data.prompts, choice: data.promptChoice}}, {
          dynamic: 1,
          eventListeners: {
            choose: [function(payload) {
              instance.emit('choose', payload);
            }],
          }
        }, []));
      }
      return m("div", {attrs: {class: "scene"}}, {dynamic: 1}, contents);
```

As a reward for putting up with such a large response, here's a slightly out of date preview of what I am making with this: http://p.cscdn.us/cookies/ It has a hard coded script, whereas the real thing will use JSON API 

That took a long time to write.

**Comment by kbrsh** [comment]
Thanks for the detailed response!

1. I'm working on fixing this, and it definitely is a problem with the behavior of an empty text node.
2. That's because moon-component-compiler (the compiler for `.moon` files) is made for the latest stable version of Moon. I really appreciate you taking the time to test out this version though.
3. This should be solved with single-file components (2)
4. I'm not really understanding here. Events don't bubble up, and are only emitted on the parent component. You can listen for an event on B and emit it back up to A.
5. `"" + content + ""` is simply a way of changing the type of something to a string. I agree that this should probably be avoided though. You'll have to trust me on this though--the compiler is the easiest method of creating a render function. It generates optimized code (using the `dynamic` property), and there are extensive tests related to optimization.
6. Totally agree on this one. I'm not sure what types of warnings/checks I should add, but whenever I run into some sort of common issue, I try my best to add one. The `"__ENV__" !== "production"` is a trick used by the build system. When building the dev version, `__ENV__` is set to "development", making the check stay. When building the production version, `__ENV__` is set to "production", making an impossible statement that is optimized by Uglify.
7. As I write the docs for v1, `m-literal` will be one of the first things that is mentioned.
8. This was a bug that has been fixed.
9. Odd. What type of template were you using? v1 ignores whitespace-only nodes.
10. Currently you can only use `m-if` and `m-else`.
11. The Todo MVC is just an inefficient demo to show how easy it is to get started. If you are making a production application with Moon you should always precompile templates (`.moon` files do this for you).

**Comment by LeviSchuck** [comment]
RE: 9.
This isn't about text nodes and the like. It's about collapsing shared conditions and components which provide a list of nodes under an otherwise purposeless parent node.

The following at runtime (where 1, 2, 3 are components that have their own nestings)
```
<div><!-- had a m-if -->
  <div>1</div>
  <div>2</div>
  <div>3</div>
</div>
```
would rather just have:
```
<!-- m-if started -->
<div>1</div>
<div>2</div>
<div>3</div>
<!-- m-if ended -->
```

I imagine that if it were with the same `m-if` on all 3 internal nodes, this nesting would not happen, but that's more to continually keep consistent and is distracting.

I have not verified moon's behavior in this particular case, just that I dread it from the angular world.

**Comment by kbrsh** [comment]
Yeah, Moon doesn't really have a way to accomplish that. You're going to need to use custom render functions for a case like that.

Honestly, in my experience I've never come across a case where I needed to do something like this. IMO it leads to more organized markup if anything.

**Comment by kbrsh** [comment]
Closing this, as I don't think making templating a plugin is a good idea and makes Moon less approachable to beginners.
