### ISSUE TITLE
m-for

### ISSUE THREAD

**Issue by 15915940450** [kbrsh/moon#145]
while install moonjs by npm, and const Moon=require('moonjs'); but something went wrong the time using directive for. ReferenceError: Moon is not defined

**Comment by 15915940450** [comment]
<div id="container">
  <ul>
    <li m-for="item in list">{{item}}</li>
  </ul>
</div>

<script src="bundle.js" charset="utf-8"></script>

//js,webpack 
const Moon=require('moonjs');
console.log(Moon);
const app6 = new Moon({
  el: '#container',
  data: {
    list: ['Item - 1', 'Item - 2', 'Item - 3', 'Item - 4']
  }
});

**Comment by kbrsh** [comment]
This is a common error, and has been fixed in v1. It's because `m-for` uses a runtime helper, `Moon.renderLoop` because Moon cannot infer the type of the variable to render.

This runtime helper has been moved so that it is in the correct scope for v1. For now, try using `global.Moon = require("moonjs")` in the file.

**Comment by 15915940450** [comment]
Thank you! it works.

**Comment by kbrsh** [comment]
Awesome!
