### ISSUE TITLE
Radio's checked attribute set, but not fully applied

### ISSUE THREAD

**Issue by Marc-oO** [kbrsh/moon#187]
Hello there,
first of all, thanks for your work ! i started a new project with your lib instead of using vuejs :)

I encounter a strange bug, or maybe i do something wrong (?) : https://codepen.io/anon/pen/wPXKrR
When you navigate the first run is perfect, but if you go to the page 1 from the last page multiple time, checked becomes wrong, in the debugger i see a 'checked' attribute but the radio is definitely not checked.

It sounds like #25 

any idea ?

**Comment by kbrsh** [comment]
It looks like the code has a number of problems.

1. The data overrides the props—you don't need to declare the props in data.
2. You pass data to the component as a string rather than its' appropriate type (boolean)
3. You have multiple child elements in the component template.

I don't think it's a problem with Moon, but I'll look into it.

**Comment by Marc-oO** [comment]
Thanks for your reply, i tried a lots a things, and it apear that is not the proper way to hanlde my use case :/
Even if i solve your checklist, this doesent work as expected.
I think there is an issue about dynamics component generation but my moonjs knowleges dont able me to go further.
Regards

**Comment by Marc-oO** [comment]
Hello,

An other issue with radio inputs : probably related to the one above
https://codepen.io/anon/pen/NXxEQq

It works at first run, but stop working correctly after the second cycle.

An other question : the "typeof" seems to be wrong ?

**Comment by kbrsh** [comment]
This was fixed in v1, using `m-literal` with a `dom` modifier. The `typeof` is not wrong, since you passed the value as a string (using template braces `{{}}` passes as a string within an attribute). Passing through `m-literal` will pass it as a number.

The fix can be seen [here](https://codepen.io/anon/pen/ypeWRw) (using the current development version of v1).

**Comment by Marc-oO** [comment]
Thanks, You are, powerful.
Regards

**Comment by kbrsh** [comment]
No problem.
