### ISSUE TITLE
Nested components

### ISSUE THREAD

**Issue by mfaessel** [kbrsh/moon#216]
Hi,

The component's doc said component can be nested
But my sample example doesnt work ?
https://jsfiddle.net/zepg5b09/13/

Did i forgot something ?

**Comment by kbrsh** [comment]
Your `uipanel` component has a template of:

```html
<p>This is a Component!</p>
```

Since this template does not contain a `uibutton`, it will not display `uibutton`. To use a `uibutton` inside, you have to change the template:

```html
<p>This is a Component! <uibutton></uibutton></p>
```

Alternatively, you can use a `<slot>`.

```js
Moon.component('uipanel', {
  template: "<p>This is a Component! <slot></slot></p>"
});
```

As you can see, I added the `slot` element in the template. This is a special component that will replace itself with the elements passed to the component like you attempted. You can use it like:

```html
<uipanel>
  <uibutton></uibutton>
</uipanel>
```

**Comment by mfaessel** [comment]
Thank you for the answer and the example.
It's clearer on how to use it.

**Comment by kbrsh** [comment]
No problem @mfaessel. I'm closing this issue, but feel free to reach out for other help.
