### ISSUE TITLE
[question] jQuery with moon

### ISSUE THREAD

**Issue by herOwOw** [kbrsh/moon#222]
Hey, i'm using moon cli and after generating the project i'm working with moon router then i face this problem. after including jQuery script into index.html and  jQuery click function for a button, if i change the router to /admin and i click on button that being attached already with jQuery's click it wont work, until i refresh the page. any solution?

**Comment by herOwOw** [comment]
the problem was in the router, since when i clicked on the router-link that lead me to the /admin page, jQuery is still loaded and the function that trigger the button exist in browser console , so when i tape again on the adresse or refresh somethings happened in the moon router then it works!
here my router setup like this:

`const Moon = require("moonjs");
require("./components/main.moon")(Moon);
require("./components/ui/admin/dashboard.moon")(Moon);
// const store = require("./store/");

const MoonRouter = require("moon-router");
Moon.use(MoonRouter);
const router = new MoonRouter({
  default: "/",
  map: {
    "/": "main",
    "/admin/": "dashboard"
  }
});

ew Moon({
  el: "#app",
  router,
});

am i messing something?

**Comment by kbrsh** [comment]
When Moon Router loads a new page, instead of actually navigating to a new page, it changes the URL and updates the page using JavaScript. The button is likely being replaced with a new one when Moon builds the DOM — this is why Moon is not compatible with JQuery in most cases because it needs full control of the DOM. This is also the case with other frameworks.

I'd suggest attaching the event with `m-on` so that Moon can update the event listener when it updates the page.

**Comment by herOwOw** [comment]
thx :) <3

**Comment by kbrsh** [comment]
No problem!
