### ISSUE TITLE
is beta 3 production ready? 

### ISSUE THREAD

**Issue by bkarlson** [kbrsh/moon#252]
Hello,
I just discovered MOON and am very excited to try it in a legacy project (as it's very hard to attach Vue or other full-blown library on top of that ol' good spaghetti :). 

However I found that the latest MOON release is from 2018, but https://github.com/kbrsh/moon/blob/master/packages/moon/dist/moon.min.js is being quietly updated to beta 3. 

Hence I wonder, is beta 3 safe to use in production or I better stick to beta 2 for now? Are there any docs about beta 3 changes? 

Cheers!

**Comment by kbrsh** [comment]
Hey!

I’d suggest sticking to beta 2 because beta 3 doesn’t have documentation yet. Documentation is the only thing left before beta 3 launches though, so it’s coming pretty soon!

However, one thing to keep in mind is that beta 3 will have a more [functional API](https://twitter.com/kbrshah/status/1145107836147359746) that will be quite different from what you’re likely used to. Keep that in mind before committing to Moon for a production project :)

**Comment by kbrsh** [comment]
[Beta 3 is out!](https://kbrsh.github.io/moon) As implied by the name, it's not production ready yet but it is fully documented and ready for use :)
